
development:
  adapter: postgresql
  encoding: unicode
  database: devjobs_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: devjobs_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: devjobs_production
  pool: 5
  host: localhost

cucumber:
  <<: *test
